name             'rackspace_anz_dd15demo'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures dd15demo'
long_description 'Installs/Configures dd15demo'
version          '0.1.0'

# depends 'platformstack'
# depends 'rackspace_sudo'
# depends 'rackspace_user'
depends 'apt'
depends 'apache2'
